### ISSUE TITLE
errors when querying wikidata due to cbk-zam

### ISSUE THREAD

**Issue by mynameisguy** [dahlia/wikidata#2]
in entity.py (line 42) there is a use in babel:
`return Locale.parse(locale.replace('-', '_'))`

while in babel the function `parse_locale` in core.py file can't parse the value cbk-zam which wikidata (and wikipedia) uses (https://cbk-zam.wikipedia.org/)

you can fix it by manually changing that function in babel. but for better solution I assume a bigger change should be considered.

(to see this bug just get the entity 'Q30' and try to print the label

**Comment by dahlia** [comment]
It was because Babel doesn't support [ISO 639-3][] (i.e. two-letter codes) but [ISO 639-1][] (i.e. three-letter codes).  One short-term solution would be to ignore languages ISO 630-1 doesn't cover but only ISO 639-3 cover, but I should consider to remove Babel from the dependencies.

[ISO 639-3]: https://en.wikipedia.org/wiki/ISO_639-3
[ISO 639-1]: https://en.wikipedia.org/wiki/ISO_639-1

**Comment by dahlia** [comment]
I applied a short-term fix of this, and the fix is released with [Wikidata 0.5.3][1] (see also [PyPI][2]). Backported to [Wikidata 0.4.4][3] ([PyPI][4]) as well.

[1]: https://wikidata.readthedocs.io/en/stable/changes.html#version-0-5-3
[2]: https://pypi.org/project/Wikidata/0.5.3/
[3]: https://wikidata.readthedocs.io/en/stable/changes.html#version-0-4-4
[4]: https://pypi.org/project/Wikidata/0.4.4/
